# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListContent_content', models.TextField()),
                ('ListContent_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListDo_title', models.CharField(max_length=100)),
                ('ListDo_remainder', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='dolist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='dolists',
        ),
        migrations.DeleteModel(
            name='DoList',
        ),
        migrations.AddField(
            model_name='listcontent',
            name='listdo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.ListDo'),
        ),
        migrations.AddField(
            model_name='tag',
            name='listdos',
            field=models.ManyToManyField(to='Notes.ListDo'),
        ),
    ]
