# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_auto_20160728_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='listdos',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='notes',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
