# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_auto_20160803_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDoTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.ListDo')),
            ],
        ),
        migrations.CreateModel(
            name='NoteTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='notetags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.Tag'),
        ),
        migrations.AddField(
            model_name='listdotags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.Tag'),
        ),
    ]
