# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_auto_20160803_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdotags',
            name='listdo',
        ),
        migrations.RemoveField(
            model_name='listdotags',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='notetags',
            name='note',
        ),
        migrations.RemoveField(
            model_name='notetags',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ListDoTags',
        ),
        migrations.DeleteModel(
            name='NoteTags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
