# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0008_auto_20160809_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
