# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 17:31
from __future__ import unicode_literals

import Notes.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0010_auto_20160809_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.ListDo')),
            ],
        ),
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.Note')),
            ],
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.Tag')),
                ('user', models.ForeignKey(default=Notes.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notetag',
            name='usertag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.UserTag'),
        ),
        migrations.AddField(
            model_name='listdotag',
            name='usertag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.UserTag'),
        ),
    ]
