# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0011_auto_20160809_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdotag',
            name='listdo',
        ),
        migrations.RemoveField(
            model_name='listdotag',
            name='usertag',
        ),
        migrations.RemoveField(
            model_name='notetag',
            name='note',
        ),
        migrations.RemoveField(
            model_name='notetag',
            name='usertag',
        ),
        migrations.DeleteModel(
            name='ListDoTag',
        ),
        migrations.DeleteModel(
            name='NoteTag',
        ),
    ]
