# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.ManyToManyField(to='Notes.Note')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.Tag')),
            ],
        ),
    ]
