# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_notetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notetag',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='notetag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='NoteTag',
        ),
    ]
