# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0008_notetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.ListDo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.Tag')),
            ],
        ),
    ]
